"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const client = new ApolloClient({
  uri: "https://api-sa-east-1.hygraph.com/v2/cliw6diuw0rl401ukasfp2yh1/master",
  cache: new InMemoryCache(),
  headers: {
    authorization: `Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdjbXMtbWFpbi1wcm9kdWN0aW9uIn0.eyJ2ZXJzaW9uIjozLCJpYXQiOjE3MDU5NTY3NDAsImF1ZCI6WyJodHRwczovL2FwaS1zYS1lYXN0LTEuaHlncmFwaC5jb20vdjIvY2xpdzZkaXV3MHJsNDAxdWthc2ZwMnloMS9tYXN0ZXIiLCJtYW5hZ2VtZW50LW5leHQuZ3JhcGhjbXMuY29tIl0sImlzcyI6Imh0dHBzOi8vbWFuYWdlbWVudC1zYS1lYXN0LTEuaHlncmFwaC5jb20vIiwic3ViIjoiNjg3YjUyODUtMDFhOC00YTM3LWFhMmMtNTZiZDNkOWQ2OTc0IiwianRpIjoiY2xycGVsaG1kMHlvNTAxbTQ5bnVnZ3c0byJ9.AmnNUhtYhi_ov4V1ABXDHf-ZKzxcBm0OOWx0T7vzqEo_qR56qP3Nv01WZ4vwqQ79Or1qcP948tTn6RWPHmjq7kfddZx1-Pna0n6m1_FoRXiDbBOGVqyBNbRy1nRNKyTlcMns6MvBUZX6gRsrJI-1nDwfh2j_7EEeHuas9xqqeiN0JQ76RxSB427Cny-qfQz-8cVOFs8ZJpz5e6exWkkBfbRkIGxMAgxSE_1ZDuv4qj6qXPyremQVAZ-pdJ8SacAEZ5hZNsjc36ZjQSY5f2k3oFvNmZvIH8FaOHb55tahB9l1I1vYpOXer27CZjC8zYO74rpyAm0ods8f5WKqi2JHfpwPFmiW5jXby-DO09RTDNtEZUit_uyky-lMY2JB4QAbNurJwj0FZqk-UYlGhfR9WO8nX57YS5cAefdW1pv1vv9Kiib9Up2uiuZ_aZ4viAcmfPlaI2xFl6xl10XgOJe3UTheoydVcskNtVBGkFCjiBdZfMAWKG76bE0Eh3_wmkvAt4fogHklr4OTXmDyx5SzJ-8KAWC7Efvdw7NQkRTtQr2iLubTRjai26ZmWGqvEXum1NRBJGawAwaK7Z0ZrhPsKhpV5bk46iiT6FlRoCzHqxCavk-5DUNwnVGZe6HQRk7JSjSb_szMG-_yyuL1q3vAJHnNLlmbdAeCd5b58BQ_W_4`,
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloProvider client={client}>
        <body className={inter.className}>{children}</body>
      </ApolloProvider>
    </html>
  );
}
